import { PriceAlertItem } from "@/lib/types";

export const sampleAlerts: PriceAlertItem[] = [
  {
    id: "al-1",
    type: "hotel",
    titleTr: "Boğaz Manzaralı Butik Otel",
    titleEn: "Boutique Hotel with Bosphorus View",
    routeOrLocationTr: "İstanbul, Beyoğlu",
    routeOrLocationEn: "Istanbul, Beyoğlu",
    originalPrice: 4200,
    currentPrice: 3150,
    currency: "TRY",
    history: [4200, 4100, 3900, 3600, 3150],
    emoji: "🏨",
  },
  {
    id: "al-2",
    type: "flight",
    titleTr: "İstanbul → Paris Direkt Uçuş",
    titleEn: "Istanbul → Paris Direct Flight",
    routeOrLocationTr: "IST → CDG",
    routeOrLocationEn: "IST → CDG",
    originalPrice: 6800,
    currentPrice: 4990,
    currency: "TRY",
    history: [6800, 6500, 5900, 5400, 4990],
    emoji: "✈️",
  },
  {
    id: "al-3",
    type: "hotel",
    titleTr: "Shibuya Merkez Otel",
    titleEn: "Central Shibuya Hotel",
    routeOrLocationTr: "Tokyo, Shibuya",
    routeOrLocationEn: "Tokyo, Shibuya",
    originalPrice: 5400,
    currentPrice: 5400,
    currency: "TRY",
    history: [5400, 5450, 5300, 5400, 5400],
    emoji: "🏨",
  },
  {
    id: "al-4",
    type: "flight",
    titleTr: "İstanbul → New York",
    titleEn: "Istanbul → New York",
    routeOrLocationTr: "IST → JFK",
    routeOrLocationEn: "IST → JFK",
    originalPrice: 18500,
    currentPrice: 15200,
    currency: "TRY",
    history: [18500, 18000, 17200, 16100, 15200],
    emoji: "✈️",
  },
];
