// Maps raw OpenStreetMap `cuisine` tag values to display labels.
// OSM tags are freeform (snake_case, sometimes multiple separated by `;`),
// so unknown tags fall back to a humanized version of the raw value.
const CUISINE_MAP: Record<string, { tr: string; en: string }> = {
  turkish: { tr: "Türk Mutfağı", en: "Turkish" },
  turkish_and_international: { tr: "Türk & Dünya Mutfağı", en: "Turkish & International" },
  kebab: { tr: "Kebap", en: "Kebab" },
  seafood: { tr: "Deniz Ürünleri", en: "Seafood" },
  fish: { tr: "Balık", en: "Fish" },
  international: { tr: "Uluslararası", en: "International" },
  regional: { tr: "Yöresel", en: "Regional" },
  local: { tr: "Yerel Mutfak", en: "Local" },
  french: { tr: "Fransız Mutfağı", en: "French" },
  bistro: { tr: "Bistro", en: "Bistro" },
  brasserie: { tr: "Brasserie", en: "Brasserie" },
  italian: { tr: "İtalyan Mutfağı", en: "Italian" },
  italian_pizza: { tr: "İtalyan Pizza", en: "Italian Pizza" },
  pizza: { tr: "Pizza", en: "Pizza" },
  pasta: { tr: "Makarna", en: "Pasta" },
  romana: { tr: "Roma Usulü", en: "Roman-style" },
  japanese: { tr: "Japon Mutfağı", en: "Japanese" },
  sushi: { tr: "Suşi", en: "Sushi" },
  ramen: { tr: "Ramen", en: "Ramen" },
  soba: { tr: "Soba", en: "Soba" },
  okonomiyaki: { tr: "Okonomiyaki", en: "Okonomiyaki" },
  gyoza: { tr: "Gyoza", en: "Gyoza" },
  chinese: { tr: "Çin Mutfağı", en: "Chinese" },
  cantonese: { tr: "Kanton Mutfağı", en: "Cantonese" },
  shanghai: { tr: "Şangay Mutfağı", en: "Shanghai" },
  taiwanese: { tr: "Tayvan Mutfağı", en: "Taiwanese" },
  korean: { tr: "Kore Mutfağı", en: "Korean" },
  thai: { tr: "Tayland Mutfağı", en: "Thai" },
  vietnamese: { tr: "Vietnam Mutfağı", en: "Vietnamese" },
  indonesian: { tr: "Endonezya Mutfağı", en: "Indonesian" },
  malaysian: { tr: "Malezya Mutfağı", en: "Malaysian" },
  indian: { tr: "Hint Mutfağı", en: "Indian" },
  curry: { tr: "Köri", en: "Curry" },
  asian: { tr: "Asya Mutfağı", en: "Asian" },
  asian_fusion: { tr: "Asya Füzyon", en: "Asian Fusion" },
  fusion_asiatique: { tr: "Asya Füzyon", en: "Asian Fusion" },
  fusion: { tr: "Füzyon", en: "Fusion" },
  eclectic: { tr: "Eklektik", en: "Eclectic" },
  spanish: { tr: "İspanyol Mutfağı", en: "Spanish" },
  tapas: { tr: "Tapas", en: "Tapas" },
  mediterranean: { tr: "Akdeniz Mutfağı", en: "Mediterranean" },
  greek: { tr: "Yunan Mutfağı", en: "Greek" },
  lebanese: { tr: "Lübnan Mutfağı", en: "Lebanese" },
  moroccan: { tr: "Fas Mutfağı", en: "Moroccan" },
  georgian: { tr: "Gürcü Mutfağı", en: "Georgian" },
  russian: { tr: "Rus Mutfağı", en: "Russian" },
  german: { tr: "Alman Mutfağı", en: "German" },
  austrian: { tr: "Avusturya Mutfağı", en: "Austrian" },
  dutch: { tr: "Hollanda Mutfağı", en: "Dutch" },
  portuguese: { tr: "Portekiz Mutfağı", en: "Portuguese" },
  american: { tr: "Amerikan Mutfağı", en: "American" },
  new_american: { tr: "Yeni Amerikan", en: "New American" },
  steak_house: { tr: "Steakhouse", en: "Steakhouse" },
  burger: { tr: "Burger", en: "Burger" },
  diner: { tr: "Diner", en: "Diner" },
  brazilian: { tr: "Brezilya Mutfağı", en: "Brazilian" },
  argentinian: { tr: "Arjantin Mutfağı", en: "Argentinian" },
  patagonian: { tr: "Patagonya Mutfağı", en: "Patagonian" },
  mexican: { tr: "Meksika Mutfağı", en: "Mexican" },
  tibetan: { tr: "Tibet Mutfağı", en: "Tibetan" },
  gastropub: { tr: "Gastropub", en: "Gastropub" },
  breakfast: { tr: "Kahvaltı", en: "Breakfast" },
  pancake: { tr: "Krep", en: "Pancakes" },
  pancakes: { tr: "Krep", en: "Pancakes" },
  crepe: { tr: "Krep", en: "Crêpe" },
  galette: { tr: "Galette", en: "Galette" },
  cake: { tr: "Pastane", en: "Cake & Bakery" },
  ice_cream: { tr: "Dondurma", en: "Ice Cream" },
  coffee_shop: { tr: "Kafe", en: "Coffee Shop" },
  bubble_tea: { tr: "Bubble Tea", en: "Bubble Tea" },
  sandwich: { tr: "Sandviç", en: "Sandwich" },
  noodle: { tr: "Erişte / Noodle", en: "Noodles" },
  organic: { tr: "Organik", en: "Organic" },
  naturel_foods: { tr: "Doğal Beslenme", en: "Natural Foods" },
  western: { tr: "Batı Mutfağı", en: "Western" },
  continental: { tr: "Kıta Avrupası", en: "Continental" },
  michelin_starred: { tr: "Michelin Yıldızlı", en: "Michelin-starred" },
  diversen: { tr: "Karma Mutfak", en: "Mixed Cuisine" },
};

function humanize(raw: string) {
  return raw.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export function labelCuisine(raw: string | null | undefined): { tr: string; en: string } {
  if (!raw) return { tr: "Restoran", en: "Restaurant" };
  const first = raw.split(";")[0].trim().toLowerCase();
  if (CUISINE_MAP[first]) return CUISINE_MAP[first];
  const humanized = humanize(first);
  return { tr: humanized, en: humanized };
}

const CUISINE_EMOJI: Record<string, string> = {
  turkish: "🥙",
  kebab: "🥙",
  seafood: "🐟",
  fish: "🐟",
  french: "🥐",
  italian: "🍝",
  pizza: "🍕",
  italian_pizza: "🍕",
  pasta: "🍝",
  japanese: "🍣",
  sushi: "🍣",
  ramen: "🍜",
  noodle: "🍜",
  chinese: "🥡",
  korean: "🍲",
  thai: "🍛",
  vietnamese: "🍜",
  indian: "🍛",
  curry: "🍛",
  spanish: "🥘",
  tapas: "🥘",
  mediterranean: "🥗",
  greek: "🥙",
  american: "🍔",
  burger: "🍔",
  steak_house: "🥩",
  mexican: "🌮",
  breakfast: "🥞",
  pancake: "🥞",
  pancakes: "🥞",
  crepe: "🥞",
  cake: "🍰",
  ice_cream: "🍨",
  coffee_shop: "☕",
  bubble_tea: "🧋",
  sandwich: "🥪",
};

export function emojiForCuisine(raw: string | null | undefined): string {
  if (!raw) return "🍽️";
  const first = raw.split(";")[0].trim().toLowerCase();
  return CUISINE_EMOJI[first] ?? "🍽️";
}
